---
functional:
- Требование 3
- Требование 4 
- Требование 8
- Требование 9
non-functional:
- Требование 2 
- Требование 1
- Требование 5 
- Требование 6 
- Требование 7
- Требование 10
implicit:
- Пользователь должен иметь возможность удалять,редактировать товар в корзине 
- Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты 
- Пользователь должен иметь возможность просмотра каталога товаров 
- Корзина пользователя должна хранится в сессии браузера для обеспечения возможности просмотра и управления покупками 



